#cloud-config
 
# Hostname management
preserve_hostname: False
hostname: {{HOSTNAME}}
 
# Users
users:
  - default
  - name: {{USER}}
    groups: ['wheel']
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - {{PUBKEY}}
      
output:
  all: ">> /var/log/cloud-init.log"
ssh_genkeytypes: ['ed25519', 'rsa']
ssh_authorized_keys:
  - {{PUBKEY}}
  
timezone: {{LOCALE}}
runcmd:
  - systemctl stop NetworkManager.service && systemctl start NetworkManager.service
  - dnf -y remove cloud-init